name = "economic-data-visualizer"
main = "worker.js"
compatibility_date = "2024-07-30"

# R2 bucket binding
[[r2_buckets]]
binding = "ECONOMIC_DATA_VISUALIZER"
bucket_name = "economic-data-visualizer"

# Environment variables (optional)
[vars]
R2_BUCKET_NAME = "economic-data-visualizer"

# Enable modules (required for ES modules)
[build.upload]
format = "modules"
main = "worker.js"

# For local development
[dev]
port = 8787
ip = "0.0.0.0"
